### ISSUE TITLE
KeyError: 'aes_kek_generation_source' 

### ISSUE THREAD

**Issue by holbre** [julesontheroad/NSC_BUILDER#125]
After the first selection (1-4) there are only error messages. The messages run through again and again and start new ones.

`-------------------------------------------------------------------------------------
"                                POWERED BY SQUIRREL                                "
"                    BASED ON THE WORK OF BLAWAR AND LUCA FRAGA                     "
                                 VERSION 0.98 (NEW)
-------------------------------------------------------------------------------------
Program's github: https://github.com/julesontheroad/NSC_BUILDER
Blawar's github:  https://github.com/blawar
Blawar's tinfoil: https://github.com/digableinc/tinfoil
Luca Fraga's github: https://github.com/LucaFraga
-------------------------------------------------------------------------------------
-----------------------------------------------
SPLITTER MODE ACTIVATED
-----------------------------------------------
***********************************************
Input "1" to add folder to list via selector
Input "2" to add file to list via selector
Input "0" to return to the MODE SELECTION MENU
***********************************************

Traceback (most recent call last):
  File "squirrel.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\nscb\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "lib\sq_tools.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\nscb\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "lib\Keys.py", line 139, in <module>
  File "lib\Keys.py", line 110, in load
KeyError: 'aes_kek_generation_source'
[6024] Failed to execute script squirrel

WHAT DO YOU WANT TO DO?
......................................................................
"DRAG ANOTHER FILE OR FOLDER AND PRESS ENTER TO ADD ITEMS TO THE LIST"

Input "1" to start processing
Input "2" to add another folder to list via selector
Input "3" to add another file to list via selector
Input "e" to exit
Input "i" to see list of files to process
Input "r" to remove some files (counting from bottom)
Input "z" to remove the whole list
......................................................................
*************************************************
Or Input "0" to return to the MODE SELECTION MENU
*************************************************`

I have already tested it on 3 PCs, the behavior is always the same. All Pyhton modules are installed.

does anyone have an idea? thank you

**Comment by deadair3210** [comment]
Make sure the key is correct, doesnt have any stray spaces or commas or anything like that, and make sure the line endings match the rest of the file

**Comment by holbre** [comment]
damn, thanks for the tip.
Unfortunately I had changed the titel.keys to keys.txt
