### ISSUE TITLE
Failed to execute script squirrel 

### ISSUE THREAD

**Issue by sacreduniverse** [julesontheroad/NSC_BUILDER#126]
Never had a problem till I tried to run a bunch of folders and ran out of space and now I keep getting this error. I pulled a new download since mine was out of date anyway. I can convert some files but not others.

**************************
DECOMPRESS A NSZ\XCZ
**************************
Traceback (most recent call last):
  File "squirrel.py", line 2786, in <module>
  File "lib\decompressor.py", line 100, in decompress_nsz
  File "Fs\Nsp.py", line 98, in __init__
  File "Fs\Pfs0.py", line 26, in __init__
  File "Fs\BaseFs.py", line 42, in __init__
  File "Fs\File.py", line 421, in __init__
  File "Fs\File.py", line 298, in __init__
  File "Fs\File.py", line 32, in __init__
  File "Fs\Nsp.py", line 284, in open
  File "Fs\Pfs0.py", line 102, in open
  File "Fs\File.py", line 69, in partition
  File "Fs\Nca.py", line 317, in open
  File "Fs\File.py", line 69, in partition
  File "Fs\Nca.py", line 149, in open
  File "lib\Keys.py", line 18, in keyAreaKey
IndexError: list index out of range
[8636] Failed to execute script squirrel
...................................................
STILL 1 FILES TO PROCESS
...................................................
Traceback (most recent call last):
  File "squirrel.py", line 2786, in <module>
  File "lib\decompressor.py", line 100, in decompress_nsz
  File "Fs\Nsp.py", line 98, in __init__
  File "Fs\Pfs0.py", line 26, in __init__
  File "Fs\BaseFs.py", line 42, in __init__
  File "Fs\File.py", line 421, in __init__
  File "Fs\File.py", line 298, in __init__
  File "Fs\File.py", line 32, in __init__
  File "Fs\Nsp.py", line 284, in open
  File "Fs\Pfs0.py", line 102, in open
  File "Fs\File.py", line 69, in partition
  File "Fs\Nca.py", line 317, in open
  File "Fs\File.py", line 69, in partition
  File "Fs\Nca.py", line 149, in open
  File "lib\Keys.py", line 18, in keyAreaKey
IndexError: list index out of range
[8556] Failed to execute script squirrel
...................................................
STILL 0 FILES TO PROCESS
...................................................
---------------------------------------------------
*********** ALL FILES WERE PROCESSED! *************
---------------------------------------------------

Input "0" to go back to the mode selection
Input "1" to exit the program

**Comment by sacreduniverse** [comment]
Repulled release after a reboot and it's working
