### ISSUE TITLE
  File "squirrel.py", line 2789, in <module>

### ISSUE THREAD

**Issue by licguzman** [julesontheroad/NSC_BUILDER#128]
I'm using windows 10, python 3.6 i have use 3.7 and 3.8 but i can't decompress nsz. I installed nsz with pip, I installed all dependencies with the .bat. I have used nsc builder x64, nsc builder86 nsc builder py version, and I have problems decompressing, can you please help me, or tell where can I get some help.?

I also have my keys.txt in the zconfig folder, and I also put them in C:\Windows\system32

DECOMPRESS A NSZ\XCZ
**************************
Decompressing C:\Users\Sdfee\Desktop\SWITCH\NSCB_098bx86\x86\game.nsz
Traceback (most recent call last):
  File "squirrel.py", line 2789, in <module>
  File "lib\decompressor.py", line 101, in decompress_nsz
  File "Fs\Nsp.py", line 9775, in decompress_direct
  File "Fs\Nsp.py", line 9575, in get_data_from_cnmt
UnboundLocalError: local variable 'titleid' referenced before assignment
[5472] Failed to execute script squirrel                                                                                ...................................................
STILL 0 FILES TO PROCESS
...................................................
---------------------------------------------------
*********** ALL FILES WERE PROCESSED! *************
---------------------------------------------------

**Comment by julesontheroad** [comment]
basically the program couldn't read the titleid in the file. Would be interesting to run a verification on it.
