### ISSUE TITLE
Feature Request - Add option to stop on full drive

### ISSUE THREAD

**Issue by deadair3210** [julesontheroad/NSC_BUILDER#133]
Could an option possibly added to stop a list if the drive is too full to process the next item sucessfully? Currently, if the drive is too full the program will generate a malformed file and will continually attempt to process the list even though its failing each file

**Comment by julesontheroad** [comment]
Yes, i think without adding all the list handle into python since the final size is calculated for the progress bar i think i could check there, then add another exchange file for the batch to check when it enters in the next loop. The exchange file idea is to avoid the progress of the list to allow processing them in the next session.

**Comment by deadair3210** [comment]
Sounds good to me! Cant Wait!

**Comment by alligatorshoes** [comment]
Hi @julesontheroad - me again (sorry!) :rofl: 

I see you've added some disk space checks in the latest version(s). Unfortunately it appears to only work on Windows and throws up a fatal error on Linux:

`Traceback (most recent call last):
  File "/home/me/github/NSC_BUILDER/py/ztools/squirrel.py", line 4224, in <module>
    dsktotal, dskused, dskfree=disk_usage(str(v_drive))
  File "/usr/lib/python3.8/shutil.py", line 1244, in disk_usage
    st = os.statvfs(path)
FileNotFoundError: [Errno 2] No such file or directory: ''
`
I'm not too familiar with GitHub so not sure how to submit a pull request (sorry), but the following appears to fix the problem.

**Before**
```python
     v_drive, v_path = os.path.splitdrive(endfile)
     dsktotal, dskused, dskfree=disk_usage(str(v_drive))	
```

**After**
```python
if sys.platform=="linux":
     v_drive = os.path.abspath(endfile)
else:
     v_drive, v_path = os.path.splitdrive(endfile)
     dsktotal, dskused, dskfree=disk_usage(str(v_drive))
```

**Comment by julesontheroad** [comment]
Thanks i'll change it later. It wasn't finished since i plan to modify part of the flow itself but i didn't tested it on my linux server.
To pull request you need to fork the repo and it should appear a button for that, anyway i'll change it based on your suggestion.

**Comment by julesontheroad** [comment]
Ok, you're right disk_usage works seems to work fine with a path to folder or a path to file. So i'll add your suggestion:
```python
if sys.platform=="linux":
     v_drive = os.path.abspath(endfile)
else:
     v_drive, v_path = os.path.splitdrive(endfile)
dsktotal, dskused, dskfree=disk_usage(str(v_drive))
```

**Comment by alligatorshoes** [comment]
No problem, thanks for all of your work on NSC_Builder, it's really appreciated!

Feel free to solve it however you prefer, I just thought I'd at least provide some code to hopefully help, but it's your project so use what you think is best. :sunglasses:

Do you accept PayPal donations?

**Comment by julesontheroad** [comment]
No, NSCB is just something i make for myself and as hobby. I'm glad if others enjoy it but I prefer not to take donations. ;)

**Comment by alligatorshoes** [comment]
Understood, well thank you again, it's a great project :smiley:
