### ISSUE TITLE
[8520] Failed to execute script squirrel

### ISSUE THREAD

**Issue by Georgenko** [julesontheroad/NSC_BUILDER#36]
From NSC_BUILDER:

********************************************************
NUT - INFO BY BLAWAR
********************************************************
92
Traceback (most recent call last):
  File "squirrel.py", line 3941, in <module>
  File "Fs\Nsp.py", line 234, in open
  File "Fs\Pfs0.py", line 61, in open
  File "Fs\File.py", line 206, in open
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\g30rg1\\Downloads\\Mortal Kombat 11 [NSP]\\Mortal Kombat 11 [0100F2200C984000][v0].nsp'
[8520] Failed to execute script squirrel

Then I tried squirrel.py:

C:\Users\g30rg1\Desktop\switch\NSCB_v085bx64\x64\ztools>python squirrel.py
Traceback (most recent call last):
  File "squirrel.py", line 38, in <module>
    import sq_tools
ModuleNotFoundError: No module named 'sq_tools'

Then I tried finding this sq_tools module but without result:

C:\Users\g30rg1\Desktop\switch\NSCB_v085bx64\x64\ztools>pip install sq_tools
Collecting sq_tools
  ERROR: Could not find a version that satisfies the requirement sq_tools (from versions: none)
ERROR: No matching distribution found for sq_tools

What the hell is happening?

**Comment by julesontheroad** [comment]
Sq_toola is not installable. That error is trying to use squirrel directly or are you trying to use NSCB?

**Comment by Georgenko** [comment]
Well I ran it separately because it was giving me errors:
Look what it gives me when i run the first option right after running the app:

-----------------------------------------------
INDIVIDUAL PROCESSING ACTIVATED
-----------------------------------------------
***********************************************
Input "0" to return to the MODE SELECTION MENU
***********************************************

Traceback (most recent call last):
  File "squirrel.py", line 38, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\W64\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "lib\sq_tools.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\W64\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "lib\Keys.py", line 94, in <module>
  File "lib\Keys.py", line 62, in load
  File "C:\Users\W64\AppData\Local\Programs\Python\Python37\lib\codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 86: invalid start byte
[8792] Failed to execute script squirrel
WHAT DO YOU WANT TO DO?
......................................................................
"DRAG ANOTHER FILE OR FOLDER AND PRESS ENTER TO ADD ITEMS TO THE LIST"

Input "1" to start processing
Input "e" to exit
Input "i" to see list of files to process
Input "r" to remove some files (counting from bottom)
Input "z" to remove the whole list
......................................................................
*************************************************
Or Input "0" to return to the MODE SELECTION MENU
*************************************************

And this runs indefinetely

**Comment by Georgenko** [comment]
I think I just fixed it. Was using the maxconsole underground keys for 6.2.0 and there were some nasty characters in there. I removed them from the keys.txt and now it gets past that.

**Comment by Georgenko** [comment]
The error below happens when you have your files inside the application folders. If you move it somewhere else (e.g. to the desktop) it won't throw it.

********************************************************
NUT - INFO BY BLAWAR
********************************************************
65
Traceback (most recent call last):
  File "squirrel.py", line 3941, in <module>
  File "Fs\Nsp.py", line 234, in open
  File "Fs\Pfs0.py", line 61, in open
  File "Fs\File.py", line 206, in open
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\g30rg1\\Desktop\\NSC_BUILDER-master\\x64\\NSCB_output\\mk.nsp'
[6756] Failed to execute script squirrel

**Comment by julesontheroad** [comment]
First one seems like it can't read the keys, did you extract them with lockpick, i had reports of issues with it and it seems to be because it doesn't split keys by lines.
If that's how ou did it, fill the template and rename to keys.txt. The verifier from the config should also show if keys are being detected correctly.
The seconf issue seems to be permission related? Maybe execute it with admin rights or don't put it on the desktop.
