### ISSUE TITLE
 No such file or directory for  exchange.txt ?

### ISSUE THREAD

**Issue by pka4916** [julesontheroad/NSC_BUILDER#95]
I have some files that I try to do  nsp -> nsz

Traceback (most recent call last):
  File "nutFs\Nca.py", line 130, in open
  File "nutFs\Titles.py", line 75, in keys
AttributeError: 'NoneType' object has no attribute 'keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "squirrel.py", line 2665, in <module>
  File "lib\compressor.py", line 513, in compress
  File "nutFs\Nsp.py", line 205, in open
  File "nutFs\Pfs0.py", line 179, in open
  File "nutFs\Nca.py", line 222, in open
  File "nutFs\File.py", line 69, in partition
  File "nutFs\Nca.py", line 136, in open
  File "lib\DBmodule.py", line 84, in retrievekey

FileNotFoundError: [Errno 2] No such file or directory: 'H:\\NSBx64\\zconfig\\DB\\exchange.txt'
[11092] Failed to execute script squirrel

**Comment by julesontheroad** [comment]
You need the latest master and python since i didn't make exe versions yet, I think that's something i fixed related to nxdumptool new ticket format that includes the elicense flag. 
The exchange file is used for xcis that includes updates so the core issue is that the key can't be read from the ticket correctly so is that issue i think or is that you don't have the masterkey that ticket has in your txt file.
I'll make a release during the weekend but if you want it now you can use the python version installing the dependencies:
https://github.com/julesontheroad/NSC_BUILDER/archive/master.zip
It also has a pararell compression option so it can compress several files at the same time.

**Comment by pka4916** [comment]
I will wait till the new x64 is there.  
I put the misc. files aside for now.

I do have the latest keys in the file.

**Comment by julesontheroad** [comment]
Forgot to say that the new release is up. If the issue was related to the ticket thing it should fix it.
